# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3632198a2e5d5ec45de67ae05ceef0c1832b5af14b2dec970742f1455857a990bb23f030d362dde1c9ea65125854faddf5154e29636c2cadb52782e0ca8ee19

test:
  secret_key_base: b8bcca21fdbcf252b95350193898836761880a0947a2aaf6a2ce6988b933522a784416df5ff02d27df9ebd4d1488586ff8f0b1fe145b71880897dfbbdb38c84d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
